In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('data_by_artist.csv')
df_info = pd.read_csv('info.csv')

In [43]:
df # mean value of artist

artist_name  artist_id  danceability    energy   valence  \
0          Frank Sinatra     792507      0.384478  0.238017  0.364288   
1      Vladimir Horowitz     119107      0.343210  0.118844  0.225951   
2            Johnny Cash     816890      0.619803  0.449381  0.680662   
3         Billie Holiday      79016      0.572637  0.201368  0.498934   
4              Bob Dylan      66915      0.512598  0.477932  0.551934   
...                  ...        ...           ...       ...       ...   
5849     Natalie La Rose    3359519      0.830000  0.520000  0.735000   
5850          Sarah Ross    3381566      0.721000  0.944000  0.626000   
5851              Rotimi    3410250      0.637000  0.501000  0.431000   
5852  Jillian Jacqueline    3455945      0.547000  0.672000  0.283000   
5853         Jaira Burns    3639618      0.566000  0.769000  0.385000   

           tempo   loudness  mode  key  acousticness  instrumentalness  \
0     110.181698 -14.271141     1    5      0.735648          0.020855   
1      94.900679 -23.193418     1    1      0.990070          0.879508   
2     115.037747 -11.593104     1   10      0.685637          0.022647   
3     109.912172 -13.225966     1    5      0.908499          0.013064   
4     126.160149 -11.184330     1    7      0.562567          0.034211   
...          ...        ...   ...  ...           ...               ...   
5849  104.990000  -8.714000     1    0      0.000792          0.000013   
5850   85.002000  -5.982000     1    8      0.013000          0.000000   
5851  103.993000  -6.148000     0    0      0.229000          0.000059   
5852  155.791000  -5.023000     1   11      0.304000          0.000000   
5853  170.036000  -4.342000     1    7      0.018300          0.000000   

      liveness  speechiness  duration_ms  popularity  count  
0     0.232106     0.049614  189179.9255   26.004383   1369  
1     0.183812     0.043360  266541.1251    3.592378   1207  
2     0.242243     0.098216  162279.2672   26.614130   1104  
3     0.217727     0.062432  185131.4530   15.621005   1095  
4     0.308978     0.064535  256713.4203   30.860806   1092  
...        ...          ...          ...         ...    ...  
5849  0.065600     0.037600  189907.0000   64.000000      1  
5850  0.320000     0.159000  262760.0000   52.000000      1  
5851  0.099000     0.187000  185461.0000   71.000000      1  
5852  0.099600     0.049600  213133.0000   58.000000      1  
5853  0.108000     0.087200  191100.0000   74.000000      1  

[5854 rows x 16 columns]

In [44]:
df_info = df_info.rename(columns={'2':'genre','1':'active_start','0':'name','Unnamed: 0':'id'})

In [45]:
df_info.loc[0][0]

74

In [46]:
col=['danceability','energy','valence','tempo','loudness','mode','key','acousticness','instrumentalness','liveness','speechiness','duration_ms','popularity','count']

In [101]:
col_c=['danceability','energy','valence','tempo','loudness','mode','key']
col_v=['acousticness','instrumentalness','liveness','speechiness']
col_d = ['duration_ms','popularity','count']

In [102]:
df_c=df[col_c]
df_v = df[col_v]
df_d = df[col_d]

In [105]:
X_c = df_c.to_numpy()

In [106]:
from sklearn import preprocessing


In [107]:
scaler = preprocessing.StandardScaler()
X_c = scaler.fit_transform(X_c)

In [108]:
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist
import seaborn as sns

In [97]:
pca = PCA(n_components=6)
pca.fit(X)
# Reduce dimensionality of X
X_reduced = pca.transform(X)

In [98]:
pca.explained_variance_ratio_

array([0.22737875, 0.12255048, 0.10038559, 0.09126714, 0.07333463,
       0.0702334 ])

In [79]:
X_reduced    

array([[-5.71544247e+04,  1.33303508e+03],
       [ 2.02067809e+04,  1.17450097e+03],
       [-8.40550735e+04,  1.06705587e+03],
       ...,
       [-6.08733007e+04, -3.56320614e+01],
       [-3.32013016e+04, -3.48501869e+01],
       [-5.52343018e+04, -3.60791548e+01]])

In [83]:
X_re=pca.inverse_transform(X_reduced)

array([[ 4.16357416e-01,  2.11980391e-01,  4.71992368e-01, ...,
         1.89179926e+05,  1.18107958e+01,  1.36868454e+03],
       [ 4.22343397e-01,  2.47990140e-01,  4.42939972e-01, ...,
         2.66541125e+05,  1.55910862e+01,  1.20741226e+03],
       [ 4.47170976e-01,  2.91063125e-01,  5.07080924e-01, ...,
         1.62279267e+05,  1.70963887e+01,  1.10374244e+03],
       ...,
       [ 5.57060730e-01,  6.02873498e-01,  5.80482120e-01, ...,
         1.85461000e+05,  3.99176992e+01,  5.13204852e-01],
       [ 5.53312530e-01,  5.99353725e-01,  5.65616699e-01, ...,
         2.13132999e+05,  4.00882519e+01,  3.00426799e-01],
       [ 5.56359045e-01,  6.02329238e-01,  5.77500033e-01, ...,
         1.91099999e+05,  3.99649190e+01, -1.36418356e-01]])

In [84]:
df_info_ve = df_info.to_numpy()
df_ve = df.to_numpy()

In [87]:
df_info_ve[0][0]

74

In [88]:
df_ve[0][1]

792507